openapi: 3.0.1
info:
  title: Firetail Middleware Example
  version: '0.1'
paths:
  /health:
    get:
      summary: Returns the status of the server
      responses:
        '200':
          description: Status of the server
          content:
            text/plain:
              schema:
                type: string
                enum: ["I'm Healthy! :)"]
  /auth-example:
    get:
      summary: An example endpoint with various types of auth applied
      security:
        - BasicAuth: []
        - ApiKeyAuth: []
        - BearerAuth: []
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
                enum: ["You're in! :)"]
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
                enum: ["401 - Unauthorised"]
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
    BearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT 