openapi: 3.0.1
info:
  title: Test Spec
  version: '0.1'
paths:
  /health:
    get:
      responses:
        '200':
          # This spec is invalid as it's missing a description
          # description: Status of the server
          content:
            text/plain:
              schema:
                type: string
                enum: ["I'm Healthy! :)"]