openapi: 3.0.1
info:
  title: Test Spec
  version: '0.1'
paths:
  /implemented:
    post:
      requestBody:
        description: A test JSON object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/exampleDocument'
          application/xml:
            schema:
              $ref: '#/components/schemas/exampleDocument'
      responses:
        '200':
          description: Status of the server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exampleDocument'
components:
  schemas:
    exampleDocument:
      type: object
      properties:
        description:
          type: string
          enum: ["test description"]
      required: [ "description" ]
      additionalProperties: false