openapi: 3.0.1
info:
  title: Firetail Middleware Example
  version: '0.1'
paths:
  /health:
    get:
      summary: Returns the status of the server
      responses:
        '200':
          description: Status of the server
          content:
            text/plain:
              schema:
                type: string
                enum: ["I'm Healthy! :)"]
        '500':
          description: Status of the server
          content:
            text/plain:
              schema:
                type: string
                enum: ["I'm Unhealthy! :("]